build: false
environment:
  matrix:
    - TOXENV: py26
    - TOXENV: py27
    - TOXENV: py33
    - TOXENV: py34
    - TOXENV: py35
platform:
  - x86
  - x64
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\ez_setup.py"
  - "c:\\python27\\python c:\\get-pip.py"
  - "c:\\python27\\Scripts\\pip install tox"
test_script:
  - "git clean -f -d -x"
  - "c:\\python27\\Scripts\\tox --version"
  - "c:\\python27\\Scripts\\pip --version"
  - "c:\\python27\\Scripts\\tox"
