environment:
  matrix:
    - JOB: "3.6 32-bit"
      PYTHON_HOME: "C:\\Python36"
      TOX_PY: py36

    - JOB: "3.7 64-bit"
      PYTHON_HOME: "C:\\Python37-x64"
      TOX_PY: py37

    - JOB: "3.8 64-bit"
      PYTHON_HOME: "C:\\Python38-x64"
      TOX_PY: py38

install:
  # Prepend Python to the PATH of this build
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"

  # check that we have the expected version and architecture for Python
  - "python --version"
  - 'python -c "import struct; print(struct.calcsize(''P'') * 8)"'

  # upgrade pip and setuptools to avoid out-of-date warnings
  - "python -m pip install --disable-pip-version-check --user --upgrade pip setuptools virtualenv"

  # install the dependencies to run the tests
  - "python -m pip install --upgrade tox pytest"

build: false

# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build wip/* branches since these are not usually used for PRs
    - /^wip\/.*$/
    # We want to build version tags as well.
    - /^v\d+\.\d+.*$/

test_script:
  - "tox -e %TOX_PY%"
