build: false
environment:
  matrix:
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
platform:
  - x86
  - x64
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - "c:\\python27\\Scripts\\pip install tox"
test_script:
  - "git clean -f -d -x"
  - "c:\\python27\\Scripts\\tox --version"
  - "c:\\python27\\Scripts\\pip --version"
  - "c:\\python27\\Scripts\\tox"
